name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "praveendev404"
          git config --global user.email "praveendev404@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/praveendev404/praveen_website.git
          npx gh-pages -d build --repo https://praveendev404:${GITHUB_TOKEN}@github.com/praveendev404/praveen_website.git
          npm run deploy